
name: Docker Image CI-test01

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running build...'
        docker build . --file Dockerfile --tag samuel1502/gitactionslab:lab1-gitaction-latest
        echo 'Pushing image...'
        docker push samuel1502/gitactionslab:lab1-gitaction-latest
        echo 'Done!'
